import rockpaperscissors as rps
import unittest

# Do not edit this file!

class TestRPS(unittest.TestCase):

    def test_tie(self):
        self.assertEqual(rps.is_better_than("paper", "paper"), None)
        self.assertEqual(rps.is_better_than("scissors", "scissors"), None)
        self.assertEqual(rps.is_better_than("rock", "rock"), None)

    def test_player0_win(self):
        self.assertEqual(rps.is_better_than("paper", "rock"), True)
        self.assertEqual(rps.is_better_than("rock", "scissors"), True)
        self.assertEqual(rps.is_better_than("scissors", "paper"), True)

    def test_player1_win(self):
        self.assertEqual(rps.is_better_than("rock", "paper"), False)
        self.assertEqual(rps.is_better_than("scissors", "rock"), False)
        self.assertEqual(rps.is_better_than("paper", "scissors"), False)

    def test_bogus_string(self):
        self.assertEqual(rps.is_better_than("PAPER", "rock"), None)
        self.assertEqual(rps.is_better_than("scissors", "giraffe"), None)
        self.assertEqual(rps.is_better_than("", ""), None)

if __name__ == '__main__':
    unittest.main()
